deployment_name: "test"
monikers: 
  personal:
    sprites:
      discord:
            ### Set these to your needs ###
            # Requests method - at least one is required
            manual_requests_enabled:  True  # Manual allows for @discord-sprite engagement
            auto_response_enabled:  False  # Auto responds automatically to relevant questions
            auto_response_cooldown: 10 # Time in minutes to cooldown between auto-responding to specific users
            auto_respond_in_threads:  False # Auto respond to messages from users in their conversations with sprite
            # Channel selection - at least one is required
            # Respond in all channels
            all_channels_enabled:  False
            all_channels_excluded_channels: [1, 1] # Exclude channels to reply in
            # Respond in specific channels
            specific_channels_enabled: True
            specific_channel_ids: [1110379342745321472, 1128776389227720795] # Requires at least one channel if enabled
            user_daily_token_limit: 30000
            # Content
            welcome_message: "ima tell you about the {}."
            short_message: "<@{}>, brevity is the soul of wit, but not of good queries. Please provide more details in your request."
            message_start: "Running request... relax, chill, and vibe a minute."
            message_end: "Generated by: gpt-4. Memory not enabled. Has no knowledge of past or current queries. For code see https://github.com/ShelbyJenkins/shelby-as-a-service."
            enabled_document_namespaces: ["deepgram", "tatum", "stackpath"]
  tatum:
    sprites:
      discord:
            ### Set these to your needs ###
            # Requests method - at least one is required
            manual_requests_enabled:  True  # Manual allows for @discord-sprite engagement
            auto_response_enabled:  False  # Auto responds automatically to relevant questions
            auto_response_cooldown: 10 # Time in minutes to cooldown between auto-responding to specific users
            auto_respond_in_threads:  False # Auto respond to messages from users in their conversations with sprite
            # Channel selection - at least one is required
            # Respond in all channels
            all_channels_enabled:  False
            all_channels_excluded_channels: [1, 1] # Exclude channels to reply in
            # Respond in specific channels
            specific_channels_enabled: True
            specific_channel_ids: [1110379342745321472, 1128776389227720795] # Requires at least one channel if enabled
            user_daily_token_limit: 30000
            # Content
            welcome_message: "ima tell you about the {}."
            short_message: "<@{}>, brevity is the soul of wit, but not of good queries. Please provide more details in your request."
            message_start: "Running request... relax, chill, and vibe a minute."
            message_end: "Generated by: gpt-4. Memory not enabled. Has no knowledge of past or current queries. For code see https://github.com/ShelbyJenkins/shelby-as-a-service."
            enabled_document_namespaces: ["deepgram", "tatum", "stackpath"]
deployment_services:
  docker_username: "shelbyjenkins"
  docker_repo: "shelby-as-a-service"
  docker_registry: "docker.io"
  stackpath_stack_id: "shelby-stack-327b67"
config_overrides:
  vectorstore_index: str = 'shelby-as-a-service'
  vectorstore_environment: str = 'us-central1-gcp'
  action_llm_model: str = 'gpt-4'
  pre_query_llm_model: str = 'gpt-4'
  query_llm_model: str = 'gpt-4'
  max_response_tokens: int = 300
  openai_timeout_seconds: float = 180.0
