name: deploy-test

on: workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
        ### Secrets ###
        # Secrets in the format of 'secrets.NAME'
        # Should be added be added to github secrets as 'NAME'

        STACKPATH_CLIENT_ID: ${{ secrets.STACKPATH_CLIENT_ID }}
        STACKPATH_API_CLIENT_SECRET: ${{ secrets.STACKPATH_API_CLIENT_SECRET }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        PERSONAL_DISCORD_SPRITE_BOT_TOKEN: ${{ secrets.PERSONAL_DISCORD_SPRITE_BOT_TOKEN }}
        TATUM_DISCORD_SPRITE_BOT_TOKEN: ${{ secrets.TATUM_DISCORD_SPRITE_BOT_TOKEN }}


        ### personal_environment_variables ###

        PERSONAL_DISCORD_MANUAL_REQUESTS_ENABLED: True
        PERSONAL_DISCORD_AUTO_RESPONSE_ENABLED: False
        PERSONAL_DISCORD_AUTO_RESPONSE_COOLDOWN: 10
        PERSONAL_DISCORD_AUTO_RESPOND_IN_THREADS: False
        PERSONAL_DISCORD_ALL_CHANNELS_ENABLED: False
        PERSONAL_DISCORD_SPECIFIC_CHANNELS_ENABLED: True
        PERSONAL_DISCORD_SPECIFIC_CHANNEL_IDS: "1110379342745321472,1128776389227720795"
        PERSONAL_DISCORD_USER_DAILY_TOKEN_LIMIT: 30000
        PERSONAL_DISCORD_WELCOME_MESSAGE: "ima tell you about the {}."
        PERSONAL_DISCORD_SHORT_MESSAGE: "<@{}>, brevity is the soul of wit, but not of good queries. Please provide more details in your request."
        PERSONAL_DISCORD_MESSAGE_START: "Running request... relax, chill, and vibe a minute."
        PERSONAL_DISCORD_MESSAGE_END: "Generated by: gpt-4. Memory not enabled. Has no knowledge of past or current queries. For code see https://github.com/ShelbyJenkins/shelby-as-a-service."
        PERSONAL_DISCORD_MONIKER: personal
        PERSONAL_DISCORD_PLATFORM: discord

        ### tatum_environment_variables ###

        TATUM_DISCORD_MANUAL_REQUESTS_ENABLED: True
        TATUM_DISCORD_AUTO_RESPONSE_ENABLED: False
        TATUM_DISCORD_AUTO_RESPONSE_COOLDOWN: 10
        TATUM_DISCORD_AUTO_RESPOND_IN_THREADS: False
        TATUM_DISCORD_ALL_CHANNELS_ENABLED: False
        TATUM_DISCORD_SPECIFIC_CHANNELS_ENABLED: True
        TATUM_DISCORD_SPECIFIC_CHANNEL_IDS: "1110379342745321472,1128776389227720795"
        TATUM_DISCORD_USER_DAILY_TOKEN_LIMIT: 30000
        TATUM_DISCORD_WELCOME_MESSAGE: "ima tell you about the {}."
        TATUM_DISCORD_SHORT_MESSAGE: "<@{}>, brevity is the soul of wit, but not of good queries. Please provide more details in your request."
        TATUM_DISCORD_MESSAGE_START: "Running request... relax, chill, and vibe a minute."
        TATUM_DISCORD_MESSAGE_END: "Generated by: gpt-4. Memory not enabled. Has no knowledge of past or current queries. For code see https://github.com/ShelbyJenkins/shelby-as-a-service."
        TATUM_DISCORD_MONIKER: tatum
        TATUM_DISCORD_PLATFORM: discord

        ### deployment_services_environment_variables ###

        DOCKER_REGISTRY: docker.io
        DOCKER_USERNAME: shelbyjenkins
        DOCKER_REPO: shelby-as-a-service
        STACKPATH_STACK_ID: shelby-stack-327b67
        DOCKER_SERVER: docker.io/shelbyjenkins/shelby-as-a-service
        DOCKER_IMAGE_PATH: shelbyjenkins/shelby-as-a-service:test-latest
        GITHUB_ACTION_WORKFLOW_NAME: deploy-test
        WORKLOAD_NAME: test-workload
        WORKLOAD_SLUG: test-slug

        ### config_overrides_variables ###

        VECTORSTORE_INDEX: str = 'shelby-as-a-service'
        VECTORSTORE_ENVIRONMENT: str = 'us-central1-gcp'
        ACTION_LLM_MODEL: str = 'gpt-4'
        PRE_QUERY_LLM_MODEL: str = 'gpt-4'
        QUERY_LLM_MODEL: str = 'gpt-4'
        MAX_RESPONSE_TOKENS: int = 300
        OPENAI_TIMEOUT_SECONDS: float = 180.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.11'

      - name: Cache pip dependencies
        uses: actions/cache@v2
        id: cache
        with:
          path: ~/.cache/pip 
          key: ${{  runner.os }}-pip-${{  hashFiles('**app/deploy/automation/test/requirements.txt') }}
          restore-keys: |
            ${{  runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f app/deploy/automation/test/requirements.txt ]; then pip install -r app/deploy/automation/test/requirements.txt; fi

      - name: Login to Docker registry
        uses: docker/login-action@v2 
        with:
          registry: docker.io
          username: shelbyjenkins
          password: ${{  secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: app/deployment/test/Dockerfile
          push: true
          tags: shelbyjenkins/shelby-as-a-service:test-latest

      - name: Add execute permissions to the script
        run: chmod +x app/deploy/automation/deploy_stackpath_container.py

      - name: Run deployment script
        run: app/deploy/automation/deploy_stackpath_container.py
