            name: personal_discord_build_deploy

            on: workflow_dispatch

            jobs:
                docker:
                    runs-on: ubuntu-latest
                    env:
                            ### Secrets ###
                            # Secrets in the format of '${{ secrets.NAME }}'
                            # Should be added be added to github secrets as 'NAME'

							STACKPATH_CLIENT_ID: ${{ secrets.STACKPATH_CLIENT_ID }}
							STACKPATH_API_CLIENT_SECRET: ${{ secrets.STACKPATH_API_CLIENT_SECRET }}
							OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
							PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
							DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
							DISCORD_TOKEN: ${{ secrets.PERSONAL_SPRITE_DISCORD_TOKEN }}

                            ### Container Environment Variables ###

							VECTORSTORE_INDEX: shelby-as-a-service
							VECTORSTORE_ENVIRONMENT: us-central1-gcp
							DISCORD_MANUAL_REQUESTS_ENABLED: True
							DISCORD_AUTO_RESPONSE_ENABLED: False
							DISCORD_AUTO_RESPONSE_COOLDOWN: 10
							DISCORD_AUTO_RESPOND_IN_THREADS: False
							DISCORD_ALL_CHANNELS_ENABLED: False
							DISCORD_SPECIFIC_CHANNELS_ENABLED: True
							DISCORD_SPECIFIC_CHANNEL_IDS: [1110379342745321472, 1128776389227720795]
							DISCORD_WELCOME_MESSAGE: "ima tell you about the {}."
							DISCORD_SHORT_MESSAGE: "<@{}>, brevity is the soul of wit, but not of good queries. Please provide more details in your request."
							DISCORD_MESSAGE_START: "Running request... relax, chill, and vibe a minute."
							DISCORD_MESSAGE_END: "Generated by: gpt-4. Memory not enabled. Has no knowledge of past or current queries. For code see https://github.com/ShelbyJenkins/shelby-as-a-service."
							DOCUMENT_SOURCES_FILEPATH: index/personal_document_sources.yaml
							VECTORSTORE_NAMESPACES: {'deepgram': 'Advanced AI services including, speech-to-text, translation, and sentiment analysis.', 'tatum': 'Blockchain and web3 infrastructure and services like RPC, NFTs, and Wallets. Supporting 70 blockchain networks with JS and C# SDKs, and an API.', 'stackpath': 'cloud infrastructure such as CDN, WAF, VMs, serverless javascript, and containers'}

                            ### Github Actions Environment Variables ###
                            DOCKER_USERNAME: shelbyjenkins
                            DOCKER_REGISTRY: docker.io
                            DOCKER_SERVER: docker.io/shelbyjenkins/shelby-as-a-service
                            DOCKER_IMAGE_PATH: shelbyjenkins/shelby-as-a-service:discord-latest
                            STACKPATH_STACK_ID: shelby-stack-327b67
                            DEPLOYMENT_TARGET: discord
                            WORKLOAD_NAME: shelby-as-a-service-personal-discord-sprite
                            WORKLOAD_SLUG: personal-discord-sprite         

                    steps:
                        - name: Checkout code
                        uses: actions/checkout@v3

                        - name: Set up Python
                        uses: actions/setup-python@v2
                        with:
                            python-version: '3.10.11'

                        - name: Cache pip dependencies
                        uses: actions/cache@v2
                        id: cache
                        with:
                            path: ~/.cache/pip
                            key: ${{  runner.os }}-pip-${{  hashFiles('**/app/deployment/discord/discord_requirements.txt') }}
                            restore-keys: |
                                ${{  runner.os }}-pip-

                        - name: Install dependencies
                        run: |
                            python -m pip install --upgrade pip
                            if [ -f app/deployment/discord/discord_requirements.txt ]; then pip install -r app/deployment/discord/discord_requirements.txt; fi

                        - name: Login to Docker registry
                        uses: docker/login-action@v2 
                        with:
                            registry: docker.io
                            username: shelbyjenkins
                            password: ${{  secrets.DOCKER_TOKEN }}

                        - name: Build and push Docker image
                        uses: docker/build-push-action@v4
                        with:
                            context: .
                            file: app/deployment/discord/Dockerfile
                            push: true
                            tags: shelbyjenkins/shelby-as-a-service:discord-latest

                        - name: Add execute permissions to the script
                        run: chmod +x app/deployment/deploy_stackpath_container.py

                        - name: Run deployment script
                        run: app/deployment/deploy_stackpath_container.py
