name: personal-deployment

on: workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest
    env:

        ### Secrets ###
        PERSONAL_SLACK_BOT_TOKEN:  ${{ secrets.PERSONAL_SLACK_BOT_TOKEN }}
        PERSONAL_DOCKER_TOKEN:  ${{ secrets.PERSONAL_DOCKER_TOKEN }}
        PERSONAL_STACKPATH_API_CLIENT_SECRET:  ${{ secrets.PERSONAL_STACKPATH_API_CLIENT_SECRET }}
        PERSONAL_PINECONE_API_KEY:  ${{ secrets.PERSONAL_PINECONE_API_KEY }}
        PERSONAL_SLACK_APP_TOKEN:  ${{ secrets.PERSONAL_SLACK_APP_TOKEN }}
        PERSONAL_STACKPATH_STACK_SLUG:  ${{ secrets.PERSONAL_STACKPATH_STACK_SLUG }}
        PERSONAL_OPENAI_API_KEY:  ${{ secrets.PERSONAL_OPENAI_API_KEY }}
        PERSONAL_STACKPATH_CLIENT_ID:  ${{ secrets.PERSONAL_STACKPATH_CLIENT_ID }}
        PERSONAL_DISCORD_BOT_TOKEN:  ${{ secrets.PERSONAL_DISCORD_BOT_TOKEN }}
        # Secrets in the format of 'secrets.NAME' with the 'NAME' portion added to your forked repos secrets. #

        REQUIRED_SECRETS: SLACK_BOT_TOKEN;DOCKER_TOKEN;STACKPATH_API_CLIENT_SECRET;PINECONE_API_KEY;SLACK_APP_TOKEN;STACKPATH_STACK_SLUG;OPENAI_API_KEY;STACKPATH_CLIENT_ID;DISCORD_BOT_TOKEN;
        DEPLOYMENT_NAME: personal

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.11'

      - name: Cache pip dependencies
        uses: actions/cache@v2
        id: cache
        with:
          path: ~/.cache/pip 
          key: ${{ runner.os }}-pip-${{  hashFiles('**app/deployments/personal/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f app/deployments/personal/requirements.txt ]; then pip install -r app/deployments/personal/requirements.txt; fi

      - name: Login to Docker registry
        uses: docker/login-action@v2 
        with:
          registry: docker.io
          username: shelbyjenkins
          password: ${{ secrets.PERSONAL_DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: app/deployments/personal/Dockerfile
          push: true
          tags: shelbyjenkins/shelby-as-a-service:personal-latest

      - name: Add execute permissions to the script
        run: chmod +x app/app.py

      - name: Run deployment script
        run: python app/app.py --deploy_container personal
