name: shelby_personal_discord_build_deploy

on: workflow_dispatch

jobs:
    docker:
        runs-on: ubuntu-latest
        env:
            # Required github secrets
            STACKPATH_CLIENT_ID: ${{ secrets.STACKPATH_CLIENT_ID }}
            STACKPATH_API_CLIENT_SECRET: ${{ secrets.STACKPATH_API_CLIENT_SECRET }}
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
            PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
            DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
            DISCORD_TOKEN: ${{ secrets.SHELBY_PERSONAL_SPRITE_DISCORD_TOKEN }}
            DISCORD_CHANNEL_ID: ${{ secrets.SHELBY_PERSONAL_SPRITE_DISCORD_CHANNEL_ID }}

            DOCKER_USERNAME: shelbyjenkins
            DOCKER_REGISTRY: docker.io
            DOCKER_SERVER: docker.io/shelbyjenkins/shelby-as-a-service
            DOCKER_IMAGE_PATH: shelbyjenkins/shelby-as-a-service:shelby_personal-latest

            STACKPATH_STACK_ID: shelby-stack-327b67

            TYPE: discord
            WORKLOAD_NAME: shelby_personal-discord-sprite
            WORKLOAD_SLUG: shelby_personal-discord-sprite
            VECTORSTORE_INDEX: shelby-as-a-service
            VECTORSTORE_NAMESPACES: '{"tatum": "blockchain and web3", "deepgram": "ai speech to text services"}'

            ACTION_LLM_MODEL: gpt-4
            QUERY_LLM_MODEL: gpt-4
            VECTORSTORE_TOP_K: 3
            OPENAI_TIMEOUT_SECONDS: 180.0
            MAX_DOCS_TOKENS: 5000
            MAX_DOCS_USED: 3
            MAX_RESPONSE_TOKENS: 300
            SELECT_OPERATIONID_LLM_MODEL: gpt-4
            CREATE_FUNCTION_LLM_MODEL: gpt-4
            POPULATE_FUNCTION_LLM_MODEL: gpt-4
            TIKTOKEN_ENCODING_MODEL: text-embedding-ada-002
            PROMPT_TEMPLATE_PATH: app/prompt_templates/
            API_SPEC_PATH: data/minified_openAPI_specs/

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.10.11'

            - name: Cache pip dependencies
              uses: actions/cache@v2
              id: cache
              with:
                  path: ~/.cache/pip
                  key: ${{  runner.os }}-pip-${{  hashFiles('**/requirements.txt') }}
                  restore-keys: |
                      ${{  runner.os }}-pip-

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

            - name: Login to Docker registry
              uses: docker/login-action@v2 
              with:
                  registry: docker.io
                  username: shelbyjenkins
                  password: ${{  secrets.DOCKER_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v4
              with:
                  context: .
                  file: app/deployment/discord/Dockerfile
                  push: true
                  tags: shelbyjenkins/shelby-as-a-service:shelby_personal-latest

            - name: Add execute permissions to the script
              run: chmod +x app/deployment/deploy_stackpath_container.py

            - name: Run deployment script
              run: app/deployment/deploy_stackpath_container.py
