name: deploy-test

on: workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest
    env:

        ### Secrets ###
        TEST_DOCKER_TOKEN:  ${{ secrets.TEST_DOCKER_TOKEN }}
        TEST_STACKPATH_CLIENT_ID:  ${{ secrets.TEST_STACKPATH_CLIENT_ID }}
        TEST_STACKPATH_API_CLIENT_SECRET:  ${{ secrets.TEST_STACKPATH_API_CLIENT_SECRET }}
        TEST_OPENAI_API_KEY:  ${{ secrets.TEST_OPENAI_API_KEY }}
        TEST_PINECONE_API_KEY:  ${{ secrets.TEST_PINECONE_API_KEY }}
        TEST_DISCORD_BOT_TOKEN:  ${{ secrets.TEST_DISCORD_BOT_TOKEN }}
        TEST_SLACK_BOT_TOKEN:  ${{ secrets.TEST_SLACK_BOT_TOKEN }}
        TEST_SLACK_APP_TOKEN:  ${{ secrets.TEST_SLACK_APP_TOKEN }}
        # Secrets in the format of 'secrets.NAME' with the 'NAME' portion added to your forked repos secrets. #

        DEPLOYMENT_VARS: '{"DEPLOYMENT_NAME": "test", "DOCKER_REGISTRY": "docker.io", "DOCKER_USERNAME": "shelbyjenkins", "DOCKER_REPO": "shelby-as-a-service", "STACKPATH_STACK_ID": "shelby-stack-327b67", "DOCKER_IMAGE_PATH": "shelbyjenkins/shelby-as-a-service:test-latest", "DOCKER_SERVER": "docker.io/shelbyjenkins/shelby-as-a-service", "WORKLOAD_NAME": "test-workload", "WORKLOAD_SLUG": "test-slug", "TEST_ENABLED_MONIKER_NAMES": ["shelby"], "TEST_INDEX_ENV": "us-central1-gcp", "TEST_INDEX_NAME": "shelby-as-a-service", "TEST_DISCORDCONFIG_DISCORD_MANUAL_REQUESTS_ENABLED": true, "TEST_DISCORDCONFIG_DISCORD_AUTO_RESPONSE_ENABLED": false, "TEST_DISCORDCONFIG_DISCORD_AUTO_RESPONSE_COOLDOWN": 10, "TEST_DISCORDCONFIG_DISCORD_AUTO_RESPOND_IN_THREADS": false, "TEST_DISCORDCONFIG_DISCORD_ALL_CHANNELS_ENABLED": false, "TEST_DISCORDCONFIG_DISCORD_SPECIFIC_CHANNELS_ENABLED": true, "TEST_DISCORDCONFIG_DISCORD_USER_DAILY_TOKEN_LIMIT": 30000, "TEST_DISCORDCONFIG_DISCORD_WELCOME_MESSAGE": "ima tell you about the {}.", "TEST_DISCORDCONFIG_DISCORD_SHORT_MESSAGE": "<@{}>, brevity is the soul of wit, but not of good queries. Please provide more details in your request.", "TEST_DISCORDCONFIG_DISCORD_MESSAGE_START": "Running request... relax, chill, and vibe a minute.", "TEST_DISCORDCONFIG_DISCORD_MESSAGE_END": "Generated by: gpt-4. Memory not enabled. Has no knowledge of past or current queries. For code see https://github.com/ShelbyJenkins/shelby-as-a-service.", "TEST_DISCORDCONFIG_DEPLOYMENT_REQUIRED_VARIABLES_": ["discord_bot_token"], "TEST_DISCORDCONFIG_MONIKER_REQUIRED_VARIABLES_": ["discord_enabled_servers", "discord_specific_channel_ids", "discord_all_channels_excluded_channels"], "TEST_DISCORDCONFIG_SPRITE_REQS_": ["ShelbyConfig"], "TEST_SHELBYCONFIG_ACTION_LLM_MODEL": "gpt-4", "TEST_SHELBYCONFIG_CEQ_DATA_DOMAIN_CONSTRAINTS_ENABLED": false, "TEST_SHELBYCONFIG_CEQ_DATA_DOMAIN_CONSTRAINTS_LLM_MODEL": "gpt-4", "TEST_SHELBYCONFIG_CEQ_DATA_DOMAIN_NONE_FOUND_MESSAGE": "Query not related to any supported data domains (aka topics). Supported data domains are:", "TEST_SHELBYCONFIG_CEQ_KEYWORD_GENERATOR_ENABLED": false, "TEST_SHELBYCONFIG_CEQ_KEYWORD_GENERATOR_LLM_MODEL": "gpt-4", "TEST_SHELBYCONFIG_CEQ_DOC_RELEVANCY_CHECK_ENABLED": false, "TEST_SHELBYCONFIG_CEQ_DOC_RELEVANCY_CHECK_LLM_MODEL": "gpt-4", "TEST_SHELBYCONFIG_CEQ_EMBEDDING_MODEL": "text-embedding-ada-002", "TEST_SHELBYCONFIG_CEQ_TIKTOKEN_ENCODING_MODEL": "text-embedding-ada-002", "TEST_SHELBYCONFIG_CEQ_DOCS_TO_RETRIEVE": 5, "TEST_SHELBYCONFIG_CEQ_DOCS_MAX_TOKEN_LENGTH": 1200, "TEST_SHELBYCONFIG_CEQ_DOCS_MAX_TOTAL_TOKENS": 3500, "TEST_SHELBYCONFIG_CEQ_DOCS_MAX_USED": 5, "TEST_SHELBYCONFIG_CEQ_MAIN_PROMPT_LLM_MODEL": "gpt-4", "TEST_SHELBYCONFIG_CEQ_MAX_RESPONSE_TOKENS": 500, "TEST_SHELBYCONFIG_OPENAI_TIMEOUT_SECONDS": 180.0, "TEST_SHELBYCONFIG_API_AGENT_SELECT_OPERATIONID_LLM_MODEL": "gpt-4", "TEST_SHELBYCONFIG_API_AGENT_CREATE_FUNCTION_LLM_MODEL": "gpt-4", "TEST_SHELBYCONFIG_API_AGENT_POPULATE_FUNCTION_LLM_MODEL": "gpt-4", "TEST_SHELBYCONFIG_DEPLOYMENT_REQUIRED_VARIABLES_": ["index_env", "index_name", "openai_api_key", "pinecone_api_key"], "TEST_SHELBYCONFIG_MONIKER_REQUIRED_VARIABLES_": [], "TEST_DISCORDCONFIG_CEQ_MAX_RESPONSE_TOKENS": 300, "TEST_SHELBY_MONIKER_ENABLED": true, "TEST_SHELBY_MONIKER_ENABLED_SPRITE_NAMES": ["discord"], "TEST_SHELBY_MONIKER_ENABLED_DATA_DOMAINS": ["deepgram", "tatum", "stackpath"], "TEST_SHELBY_DISCORDCONFIG_DISCORD_ENABLED_SERVERS": [1132125546340421733, 397459590767312906], "TEST_SHELBY_DISCORDCONFIG_DISCORD_SPECIFIC_CHANNEL_IDS": [1110379342745321472, 1128776389227720795, 1133913077268627526], "TEST_SHELBY_DISCORDCONFIG_DISCORD_ALL_CHANNELS_EXCLUDED_CHANNELS": [null], "TEST_SHELBY_DISCORDCONFIG_CEQ_DOCS_MAX_TOTAL_TOKENS": 250}'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.11'

      - name: Cache pip dependencies
        uses: actions/cache@v2
        id: cache
        with:
          path: ~/.cache/pip 
          key: ${{  runner.os }}-pip-${{  hashFiles('**deployments/test/requirements.txt') }}
          restore-keys: |
            ${{  runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f deployments/test/requirements.txt ]; then pip install -r deployments/test/requirements.txt; fi

      - name: Login to Docker registry
        uses: docker/login-action@v2 
        with:
          registry: docker.io
          username: shelbyjenkins
          password: ${{  secrets.TEST_DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: deployments/test/Dockerfile
          push: true
          tags: shelbyjenkins/shelby-as-a-service:test-latest

      - name: Add execute permissions to the script
        run: chmod +x app/deployment_maker/deploy_stackpath_container.py

      - name: Run deployment script
        run: app/deployment_maker/deploy_stackpath_container.py
